version: '3'
services:
  mysql:
    image: mariadb:10.7.3
    ports:
      - "13306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rtpass
      - MYSQL_DATABASE=gwuser
